remote_theme: covid-at-home/common
title: COVID @ Home
description: A collaborative guide to COVID-19 care
url: https://covid-at-home.info
slug: covid-at-home
goatcounter: covid_at_home

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME